from backend.schemas import PlayerExample, PlayerStats


EXAMPLES = [
    PlayerExample(
        name="LeBron James",
        actual_all_star=True,
        stats=PlayerStats(
            age=19,
            gp=79,
            pts=1654,
            reb=432,
            ast=465,
            stl=130,
            blk=58,
            min=3120,
            fg_pct=0.417,
            fg3_pct=0.290,
            ft_pct=0.754,
        ),
    ),
    PlayerExample(
        name="Stephen Curry",
        actual_all_star=True,
        stats=PlayerStats(
            age=22,
            gp=80,
            pts=1399,
            reb=356,
            ast=472,
            stl=152,
            blk=19,
            min=2896,
            fg_pct=0.462,
            fg3_pct=0.437,
            ft_pct=0.885,
        ),
    ),
    PlayerExample(
        name="Giannis Antetokounmpo",
        actual_all_star=True,
        stats=PlayerStats(
            age=19,
            gp=77,
            pts=525,
            reb=339,
            ast=150,
            stl=60,
            blk=61,
            min=1897,
            fg_pct=0.414,
            fg3_pct=0.347,
            ft_pct=0.683,
        ),
    ),
    PlayerExample(
        name="Anthony Edwards",
        actual_all_star=True,
        stats=PlayerStats(
            age=19,
            gp=72,
            pts=1392,
            reb=336,
            ast=211,
            stl=82,
            blk=36,
            min=2314,
            fg_pct=0.417,
            fg3_pct=0.329,
            ft_pct=0.776,
        ),
    ),
    PlayerExample(
        name="Ronnie Grandison",
        actual_all_star=False,
        stats=PlayerStats(
            age=24,
            gp=72,
            pts=177,
            reb=92,
            ast=42,
            stl=18,
            blk=3,
            min=528,
            fg_pct=0.415,
            fg3_pct=0.000,
            ft_pct=0.738,
        ),
    ),
]
